import { StyleSheet } from "react-native";
import { colors, fonts, radius, shadow, spacing, typography } from "../../utils/theme";

export const sellerStyles = StyleSheet.create({
  centered: {
    alignItems: "center",
    backgroundColor: colors.background,
    flex: 1,
    gap: spacing.lg,
    justifyContent: "center",
    padding: spacing.xl,
  },
  content: {
    gap: spacing.xl,
    paddingBottom: spacing.xxxl,
  },
  workspaceStatusPill: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.round,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 7,
  },
  workspaceStatusPillInactive: { backgroundColor: "#FFF1F2", borderColor: "#FECDD3" },
  workspaceStatusDot: { backgroundColor: colors.success, borderRadius: radius.round, height: 8, width: 8 },
  workspaceStatusDotInactive: { backgroundColor: colors.danger, shadowColor: colors.danger, shadowOpacity: 0.28, shadowRadius: 4 },
  workspaceStatusText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  workspaceStatusTextInactive: { color: colors.danger },
  workspaceTopbar: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  workspaceTopbarActions: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  workspaceChatButton: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    position: "relative",
    width: 38,
  },
  workspaceChatButtonUnread: {
    backgroundColor: "#FFFBEB",
    borderColor: "#FDE68A",
  },
  workspaceChatBadge: {
    alignItems: "center",
    backgroundColor: colors.warning,
    borderColor: colors.card,
    borderRadius: radius.round,
    borderWidth: 2,
    height: 19,
    justifyContent: "center",
    minWidth: 19,
    paddingHorizontal: 3,
    position: "absolute",
    right: -6,
    top: -6,
  },
  workspaceChatBadgeText: {
    color: "#4A2B00",
    fontFamily: fonts.extraBold,
    fontSize: 9,
    fontWeight: "800",
  },
  choiceCard: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 98,
    padding: spacing.lg,
    width: "100%",
    ...shadow,
  },
  choiceCardSecondary: {
    backgroundColor: "#F8FAFC",
    shadowOpacity: 0,
  },
  choiceArrow: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.round,
    borderWidth: 1,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  choiceCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  choiceIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.round,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  choiceLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  choiceMeta: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.small,
    lineHeight: 18,
  },
  documentHint: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.md,
  },
  documentHintText: {
    color: colors.primaryDark,
    flex: 1,
    fontFamily: fonts.semiBold,
    fontSize: typography.small,
    fontWeight: "600",
  },
  destinationDivider: {
    backgroundColor: colors.border,
    height: 1,
    width: "100%",
  },
  destinationSectionLabel: {
    color: colors.textMuted,
    fontFamily: fonts.bold,
    fontSize: 10,
    fontWeight: "700",
  },
  disabledAction: {
    opacity: 0.55,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 20,
    borderWidth: 1,
    gap: spacing.sm,
    padding: spacing.xl,
    ...shadow,
  },
  emptyText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.small,
    lineHeight: 19,
    textAlign: "center",
  },
  emptyTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.label,
    fontWeight: "700",
  },
  hero: {
    borderColor: colors.border,
    borderRadius: 28,
    borderWidth: 1,
    gap: spacing.md,
    overflow: "hidden",
    padding: spacing.xl,
    ...shadow,
  },
  heroCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  heroHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  heroIcon: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.primaryLight,
    borderRadius: radius.round,
    borderWidth: 1,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  inputLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.semiBold,
    fontSize: typography.label,
    fontWeight: "600",
  },
  imagePickerCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  imagePickerField: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 86,
    padding: spacing.md,
  },
  imagePickerHelper: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
  },
  imagePickerImage: {
    height: "100%",
    width: "100%",
  },
  imagePickerLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.label,
    fontWeight: "700",
  },
  imagePickerPreview: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.md,
    borderWidth: 1,
    height: 58,
    justifyContent: "center",
    overflow: "hidden",
    width: 58,
  },
  imagePickerPreviewWide: {
    width: 92,
  },
  kicker: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: typography.caption,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  loadingText: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.small,
  },
  miniStat: {
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
    padding: spacing.md,
  },
  miniStatLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.caption,
  },
  miniStatValue: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  modal: {
    backgroundColor: colors.card,
    borderRadius: 24,
    gap: spacing.lg,
    maxHeight: "92%",
    maxWidth: 520,
    padding: spacing.lg,
    width: "100%",
    ...shadow,
  },
  managerModal: {
    maxHeight: "94%",
  },
  managerAction: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: spacing.sm,
    minHeight: 78,
    minWidth: 96,
    padding: spacing.md,
  },
  managerActionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  courierHub: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  courierHubHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  courierHubActions: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  courierActionCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  courierActionEyebrow: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 9,
    fontWeight: "700",
  },
  courierActionIcon: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.round,
    height: 44,
    justifyContent: "center",
    width: 44,
  },
  courierActionText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
  },
  courierActionTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.label,
    fontWeight: "800",
  },
  courierPrimaryAction: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.lg,
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "center",
    minHeight: 42,
  },
  courierPrimaryActionText: {
    color: colors.card,
    fontFamily: fonts.bold,
    fontSize: typography.small,
  },
  courierSecondaryAction: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "center",
    minHeight: 42,
  },
  courierSecondaryActionText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.small,
  },
  managerMetric: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minWidth: 68,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
  },
  managerMetricHighlight: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
  },
  managerMetricDanger: {
    backgroundColor: colors.dangerSoft,
    borderColor: "#FECACA",
  },
  managerMetricLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: 9,
    textAlign: "center",
  },
  managerMetrics: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  managerMetricValue: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  managerMetricValueDanger: { color: colors.danger },
  managerActionIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  managerActionText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    textAlign: "center",
  },
  availabilityCard: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 76,
    padding: spacing.md,
  },
  availabilityCardClosed: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FED7AA",
  },
  availabilityCopy: { flex: 1, gap: 3, minWidth: 0 },
  availabilityIcon: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: radius.round,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  availabilityIconClosed: { backgroundColor: "#FFEDD5" },
  availabilityText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  availabilityTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  commercialNotice: {
    alignItems: "flex-start",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.md,
  },
  commercialNoticeCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  commercialNoticeText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.small,
    lineHeight: 19,
  },
  commercialNoticeTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.label,
    fontWeight: "700",
  },
  catalogMetric: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minWidth: 90,
    padding: spacing.md,
  },
  catalogMetricAlert: {
    backgroundColor: "#FFF7ED",
    borderColor: "#FED7AA",
  },
  catalogMetricLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  catalogMetrics: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  catalogMetricValue: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  crmActionDisabled: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 38,
    opacity: 0.72,
    paddingHorizontal: spacing.md,
  },
  crmActionText: {
    color: colors.textMuted,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  crmActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  crmEmpty: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.md,
  },
  crmEmptyCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  crmEmptyIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 46,
    justifyContent: "center",
    width: 46,
  },
  crmFilterButton: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 34,
    paddingHorizontal: spacing.md,
  },
  crmFilterButtonActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  crmFilterButtonWithBadge: {
    borderColor: colors.primaryLight,
  },
  crmFilterBadge: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.round,
    height: 18,
    justifyContent: "center",
    minWidth: 18,
    paddingHorizontal: 5,
  },
  crmFilterBadgeActive: {
    backgroundColor: colors.card,
  },
  crmFilterBadgeText: {
    color: colors.card,
    fontFamily: fonts.extraBold,
    fontSize: 10,
    fontWeight: "800",
  },
  crmFilterBadgeTextActive: {
    color: colors.primaryDark,
  },
  crmFilters: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  crmFilterText: {
    color: colors.textSecondary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    lineHeight: 32,
  },
  crmFilterTextActive: {
    color: colors.card,
  },
  crmHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  crmPanel: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.lg,
    ...shadow,
  },
  crmPriority: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.lg,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 68,
    padding: spacing.md,
  },
  crmPriorityCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  crmPriorityIcon: {
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.14)",
    borderRadius: radius.round,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  crmPriorityText: {
    color: "rgba(255, 255, 255, 0.76)",
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
  },
  crmPriorityTitle: {
    color: colors.card,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  crmOverview: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    borderTopColor: colors.border,
    borderTopWidth: 1,
    flexDirection: "row",
    paddingVertical: spacing.md,
  },
  crmOverviewAside: {
    alignItems: "flex-end",
    borderLeftColor: colors.border,
    borderLeftWidth: 1,
    gap: 2,
    minWidth: 100,
    paddingLeft: spacing.md,
  },
  crmOverviewAsideLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  crmOverviewAsideValue: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  crmOverviewCopy: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  crmOverviewLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.caption,
  },
  crmOverviewValue: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h2,
    fontWeight: "800",
  },
  crmPipeline: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  crmStage: {
    alignItems: "center",
    backgroundColor: "#F8FAF9",
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    flexGrow: 1,
    flexBasis: "21%",
    gap: 2,
    justifyContent: "center",
    minHeight: 74,
    minWidth: 70,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.sm,
  },
  crmStageActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  crmStageLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.bold,
    fontSize: 10,
    fontWeight: "700",
    textAlign: "center",
  },
  crmStageValue: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  crmStageLabelActive: {
    color: colors.card,
  },
  crmStageValueActive: {
    color: colors.card,
  },
  crmSubtitle: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
    marginTop: 2,
  },
  crmViewCount: {
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: radius.round,
    height: 22,
    justifyContent: "center",
    minWidth: 22,
    paddingHorizontal: 6,
  },
  crmViewCountActive: {
    backgroundColor: colors.primaryDark,
  },
  crmViewCountText: {
    color: colors.textSecondary,
    fontFamily: fonts.extraBold,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  crmViewCountTextActive: {
    color: colors.card,
  },
  crmViewTab: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 46,
    paddingHorizontal: spacing.md,
  },
  crmViewTabActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
  },
  crmViewTabs: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  crmViewTabText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  crmViewTabTextActive: {
    color: colors.primaryDark,
  },
  orderBuyer: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  orderActionButton: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.round,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 34,
    paddingHorizontal: spacing.sm,
  },
  orderActionDanger: {
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
  },
  orderActionText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  orderActionTextDanger: {
    color: colors.danger,
  },
  orderActionsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  orderAttentionLine: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.md,
    flexDirection: "row",
    gap: spacing.xs,
    marginTop: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  orderAttentionText: {
    color: colors.primaryDark,
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    lineHeight: 17,
  },
  orderAddress: {
    color: colors.textMuted,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
  },
  orderCode: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  orderCodePill: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    flexDirection: "row",
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
  },
  orderChatAvatar: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  orderChatBody: {
    flexGrow: 1,
    gap: 10,
    justifyContent: "flex-end",
    padding: spacing.sm,
  },
  orderChatBubbleSpacer: {
    height: spacing.xs,
  },
  orderChatButton: {
    backgroundColor: "#EFF6FF",
    borderColor: "#BFDBFE",
  },
  orderChatHeader: {
    alignItems: "center",
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    paddingBottom: spacing.md,
  },
  orderChatHeaderCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  orderChatHint: {
    color: colors.textWeak,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
    textAlign: "center",
  },
  orderChatInput: {
    color: colors.textPrimary,
    flex: 1,
    fontFamily: fonts.regular,
    fontSize: typography.small,
    maxHeight: 86,
    minHeight: 42,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    textAlignVertical: "top",
  },
  orderChatInputRow: {
    alignItems: "flex-end",
    backgroundColor: colors.card,
    borderColor: colors.primaryLight,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.sm,
  },
  orderChatModal: {
    backgroundColor: colors.card,
    borderRadius: 18,
    gap: spacing.md,
    height: "92%",
    maxHeight: "92%",
    maxWidth: 520,
    padding: spacing.md,
    width: "100%",
    ...shadow,
  },
  orderChatScroll: {
    backgroundColor: "#FBFCFB",
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    minHeight: 96,
  },
  orderChatTimeline: {
    flex: 1,
    minHeight: 96,
    position: "relative",
  },
  orderChatSend: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.round,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  orderChatSendDisabled: {
    backgroundColor: colors.textWeak,
  },
  orderChatSubtitle: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.caption,
  },
  orderChatText: {
    color: colors.info,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  orderChatTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  orderCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  orderFooter: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
    justifyContent: "space-between",
  },
  orderHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
  },
  orderIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  orderIconHistory: {
    backgroundColor: "#F3F4F6",
  },
  orderIconAttention: {
    backgroundColor: colors.primaryDark,
  },
  orderItems: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  orderList: {
    gap: spacing.md,
  },
  orderPanel: {
    backgroundColor: colors.backgroundSoft,
    borderColor: colors.primaryLight,
    borderRadius: 18,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  orderPanelSubtitle: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    marginTop: 2,
  },
  orderPayment: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.caption,
  },
  ordersBadge: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.round,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  ordersBadgeText: {
    color: colors.card,
    fontFamily: fonts.extraBold,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  orderStat: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    justifyContent: "center",
    minHeight: 62,
    padding: spacing.sm,
  },
  orderStatLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  orderStats: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  orderStatValue: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
    textAlign: "center",
  },
  orderStatus: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: 10,
    fontWeight: "800",
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
  },
  orderStatusGroup: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  orderUnreadBadge: {
    alignItems: "center",
    backgroundColor: colors.info,
    borderRadius: radius.round,
    height: 22,
    justifyContent: "center",
    minWidth: 22,
    paddingHorizontal: 6,
  },
  orderUnreadBadgeText: {
    color: colors.card,
    fontFamily: fonts.extraBold,
    fontSize: 10,
    fontWeight: "800",
  },
  orderTotal: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  optionalDetailsButton: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 60,
    padding: spacing.md,
  },
  optionalDetailsCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  optionalDetailsIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  optionalDetailsText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  optionalDetailsTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  storeOrderRow: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.md,
  },
  storeOrderRowAttention: {
    backgroundColor: "#F4FCF8",
    borderColor: colors.primaryLight,
  },
  storeOrderRowHistory: {
    backgroundColor: "#FAFAFA",
  },
  modalActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
    justifyContent: "flex-end",
  },
  modalBackdrop: {
    alignItems: "center",
    backgroundColor: "rgba(15, 23, 42, 0.36)",
    flex: 1,
    justifyContent: "center",
    padding: spacing.lg,
  },
  modalBody: {
    gap: spacing.lg,
    paddingBottom: spacing.xs,
  },
  modalClose: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderRadius: radius.round,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  modalError: {
    color: colors.danger,
    fontFamily: fonts.medium,
    fontSize: typography.small,
  },
  modalHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalKicker: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  modalTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h2,
    fontWeight: "800",
  },
  scheduleClosedPill: {
    alignItems: "center",
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  scheduleClosedText: {
    color: colors.textMuted,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  scheduleDayLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    minWidth: 26,
  },
  scheduleDayRow: {
    alignItems: "center",
    borderTopColor: colors.border,
    borderTopWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "space-between",
    minHeight: 58,
    paddingVertical: spacing.sm,
  },
  scheduleDayToggle: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  scheduleDays: { gap: 0 },
  scheduleEditor: {
    backgroundColor: "#FAFFFC",
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
  },
  scheduleHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    paddingVertical: spacing.md,
  },
  scheduleHeaderCopy: { flex: 1, gap: 2, minWidth: 0 },
  scheduleHeaderIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  scheduleSubtitle: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  scheduleTimeInput: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    height: 38,
    paddingHorizontal: spacing.sm,
    textAlign: "center",
    width: 62,
  },
  scheduleTimeRange: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.xs,
  },
  scheduleTimeSeparator: {
    color: colors.textMuted,
    fontFamily: fonts.medium,
    fontSize: 10,
  },
  scheduleTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  scheduleSummary: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 64,
    padding: spacing.md,
  },
  scheduleSummaryAction: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  scheduleSummaryCopy: { flex: 1, gap: 2, minWidth: 0 },
  scheduleSummaryIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  scheduleSummaryText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  scheduleSummaryTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  noticeCard: {
    alignItems: "flex-start",
    backgroundColor: colors.warningSoft,
    borderColor: "#FED7AA",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.lg,
  },
  noticeText: {
    color: "#92400E",
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: typography.small,
    lineHeight: 19,
  },
  pressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  formColumn: {
    flex: 1,
    minWidth: 142,
  },
  formTwoColumns: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.md,
  },
  optionBlock: {
    gap: spacing.sm,
  },
  optionChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  optionLabel: {
    color: colors.textPrimary,
    fontFamily: fonts.semiBold,
    fontSize: typography.label,
    fontWeight: "600",
  },
  productFormHelp: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
  },
  productFormSection: {
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    gap: spacing.md,
    padding: spacing.md,
  },
  productFormSectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
  },
  productFormSectionTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.label,
    fontWeight: "800",
  },
  productManageCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  productManageMain: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: spacing.md,
    minWidth: 0,
  },
  productManageMeta: {
    color: colors.textMuted,
    fontFamily: fonts.medium,
    fontSize: typography.caption,
  },
  productManageRow: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.md,
    ...shadow,
  },
  productThumb: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    overflow: "hidden",
    width: 48,
  },
  productThumbImage: {
    height: "100%",
    width: "100%",
  },
  productOptionChip: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    minHeight: 36,
    minWidth: 58,
    justifyContent: "center",
    paddingHorizontal: spacing.md,
  },
  productOptionChipActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  productOptionChipText: {
    color: colors.textSecondary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  productOptionChipTextActive: {
    color: colors.card,
  },
  productToggleIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  productToggleIconActive: {
    backgroundColor: colors.primaryDark,
  },
  productToggleRow: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    minHeight: 52,
    minWidth: 178,
    padding: spacing.sm,
  },
  productToggleRowActive: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
  },
  productToggleText: {
    color: colors.textSecondary,
    flex: 1,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    lineHeight: 16,
  },
  productToggleTextActive: {
    color: colors.textPrimary,
  },
  refreshButton: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  qrExpirationCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  qrExpirationHint: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.md,
  },
  qrExpirationIcon: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: radius.round,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  qrExpirationText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 16,
  },
  qrExpirationTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  quickChargeHeading: {
    gap: 2,
  },
  quickChargeDetails: {
    gap: spacing.lg,
  },
  quickChargeMeta: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  quickChargeOption: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    gap: 2,
    justifyContent: "center",
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  quickChargeOptionPrice: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: 10,
    fontWeight: "700",
  },
  quickChargeOptionSelected: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  quickChargeOptionText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  quickChargeOptionTextSelected: {
    color: colors.card,
  },
  quickChargeOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  quickChargeSection: {
    gap: spacing.sm,
  },
  quickChargeTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  quickChargeSubmit: {
    minHeight: 58,
    width: "100%",
  },
  saleAmount: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.label,
    fontWeight: "800",
    textAlign: "right",
  },
  saleCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  saleIcon: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  saleMeta: {
    color: colors.textMuted,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  saleRow: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.md,
    ...shadow,
  },
  deleteStoreButton: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "center",
    minHeight: 48,
    paddingHorizontal: spacing.lg,
  },
  deleteStoreText: {
    color: colors.danger,
    fontFamily: fonts.bold,
    fontSize: typography.label,
    fontWeight: "700",
  },
  saleStatusPill: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    maxWidth: 104,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  saleStatus: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
    textAlign: "center",
  },
  saleTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.label,
    fontWeight: "700",
  },
  saleValues: {
    alignItems: "flex-end",
    gap: spacing.xs,
    maxWidth: 122,
    minWidth: 88,
  },
  salesList: {
    gap: spacing.md,
  },
  storeActionButton: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  storeActionDanger: {
    backgroundColor: "#FEF2F2",
  },
  storeActions: {
    flexDirection: "row",
    gap: spacing.xs,
  },
  storeBanner: {
    backgroundColor: colors.primarySoft,
    borderRadius: 18,
    height: 148,
    overflow: "hidden",
    width: "100%",
  },
  storeBannerFallback: {
    alignItems: "center",
    height: "100%",
    justifyContent: "center",
    width: "100%",
  },
  storeBannerImage: {
    height: "100%",
    width: "100%",
  },
  storeLogo: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.primaryLight,
    borderRadius: 18,
    borderWidth: 1,
    height: 64,
    justifyContent: "center",
    overflow: "hidden",
    width: 64,
  },
  storeLogoImage: {
    height: "100%",
    width: "100%",
  },
  storeManagerBadges: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  storeManagerTab: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: spacing.xs,
    justifyContent: "center",
    minHeight: 48,
    minWidth: 0,
    paddingHorizontal: spacing.sm,
  },
  storeManagerTabActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  storeManagerTabBadge: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    minWidth: 24,
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
  },
  storeManagerTabBadgeActive: {
    backgroundColor: colors.card,
  },
  storeManagerTabBadgeText: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: 10,
    fontWeight: "800",
  },
  storeManagerTabBadgeTextActive: {
    color: colors.primaryDark,
  },
  storeManagerTabs: {
    backgroundColor: "#F8FAFC",
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    padding: spacing.xs,
  },
  storeManagerTabText: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.caption,
    fontWeight: "800",
  },
  storeManagerTabTextActive: {
    color: colors.card,
  },
  storeManagerCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  storeManagerHero: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.lg,
    borderWidth: 1,
    gap: spacing.md,
    overflow: "hidden",
    padding: spacing.md,
    ...shadow,
  },
  storeManagerInfo: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  storeManagerMeta: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.small,
  },
  storeManagerName: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  storeTabPanel: {
    gap: spacing.lg,
  },
  storeTabSubtitle: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
    lineHeight: 17,
    marginTop: 2,
  },
  storeWorkspace: {
    gap: spacing.lg,
  },
  storeRow: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    minHeight: 82,
    padding: spacing.md,
    ...shadow,
  },
  storeNewOrderBadge: {
    alignItems: "center",
    backgroundColor: colors.danger,
    borderRadius: radius.round,
    flexDirection: "row",
    gap: spacing.xs,
    maxWidth: 102,
    minHeight: 30,
    paddingHorizontal: spacing.sm,
  },
  storeNewOrderBadgeText: {
    color: colors.card,
    fontFamily: fonts.bold,
    fontSize: 11,
    fontWeight: "700",
  },
  storeRowArrow: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  sectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  sectionActions: { alignItems: "center", flexDirection: "row", gap: spacing.xs },
  sectionTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  managerBadge: {
    backgroundColor: colors.primarySoft,
    borderColor: colors.primaryLight,
    borderRadius: radius.round,
    borderWidth: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
  },
  managerBadgeText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  sellerChatAvatar: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  sellerChatBubble: {
    borderRadius: 16,
    gap: 3,
    maxWidth: "80%",
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  sellerChatBubbleClient: {
    backgroundColor: colors.card,
    borderBottomLeftRadius: radius.sm,
    borderColor: colors.border,
    borderWidth: 1,
  },
  sellerChatBubbleStore: {
    backgroundColor: colors.primaryDark,
    borderBottomRightRadius: radius.sm,
  },
  sellerChatBubbleText: {
    color: colors.textPrimary,
    fontFamily: fonts.regular,
    fontSize: typography.small,
    lineHeight: 20,
  },
  sellerChatBubbleTextStore: {
    color: colors.card,
  },
  sellerChatBubbleTime: {
    alignSelf: "flex-end",
    color: colors.textWeak,
    fontFamily: fonts.medium,
    fontSize: 9,
  },
  sellerChatBubbleTimeStore: {
    color: "rgba(255,255,255,0.68)",
  },
  sellerChatBubbleTitle: {
    color: colors.primaryDark,
    fontFamily: fonts.extraBold,
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  sellerChatBubbleTitleStore: {
    color: colors.card,
  },
  sellerChatRow: {
    alignItems: "flex-end",
    flexDirection: "row",
    gap: spacing.sm,
  },
  sellerChatRowStore: {
    justifyContent: "flex-end",
  },
  segmentBlock: {
    gap: spacing.sm,
  },
  segmentChip: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.round,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.xs,
    minHeight: 38,
    paddingHorizontal: spacing.md,
  },
  segmentChipActive: {
    backgroundColor: colors.primaryDark,
    borderColor: colors.primaryDark,
  },
  segmentChipText: {
    color: colors.textPrimary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  segmentChipTextActive: {
    color: colors.card,
  },
  segmentChipMeta: {
    color: colors.textMuted,
    fontFamily: fonts.regular,
    fontSize: 10,
  },
  segmentList: {
    gap: spacing.sm,
    paddingRight: spacing.lg,
  },
  segmentListWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
  },
  segmented: {
    backgroundColor: "#F3F4F6",
    borderRadius: radius.lg,
    flexDirection: "row",
    gap: spacing.sm,
    padding: spacing.xs,
  },
  segmentedOption: {
    alignItems: "center",
    borderRadius: radius.lg,
    flex: 1,
    flexDirection: "row",
    gap: spacing.sm,
    justifyContent: "center",
    minHeight: 42,
  },
  segmentedOptionActive: {
    backgroundColor: colors.primaryDark,
  },
  segmentedText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.small,
    fontWeight: "700",
  },
  segmentedTextActive: {
    color: colors.card,
  },
  sellChoiceGrid: {
    gap: spacing.md,
    flexDirection: "column",
  },
  sellerAvatar: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  sellerCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 22,
    borderWidth: 1,
    gap: spacing.lg,
    padding: spacing.lg,
    ...shadow,
  },
  sellerCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  sellerHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.md,
  },
  sellerMeta: {
    color: colors.textSecondary,
    fontFamily: fonts.medium,
    fontSize: typography.small,
  },
  sellerNotificationCard: {
    alignItems: "center",
    backgroundColor: "#FEF2F2",
    borderColor: "#FECACA",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.md,
    padding: spacing.md,
  },
  sellerNotificationCopy: {
    flex: 1,
    gap: spacing.xs,
    minWidth: 0,
  },
  sellerNotificationIcon: {
    alignItems: "center",
    backgroundColor: colors.danger,
    borderRadius: radius.round,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  sellerNotificationText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.small,
    lineHeight: 19,
  },
  sellerNotificationTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.label,
    fontWeight: "800",
  },
  sellerName: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.h3,
    fontWeight: "800",
  },
  sellerStats: {
    flexDirection: "row",
    gap: spacing.sm,
  },
  orderProposalBar: {
    alignItems: "center",
    backgroundColor: colors.primarySoft,
    borderBottomColor: colors.primaryLight,
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  orderProposalBarCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  orderProposalBarIcon: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderRadius: radius.round,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  orderProposalBarText: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.caption,
  },
  orderProposalBarTitle: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: typography.small,
    fontWeight: "800",
  },
  orderProposalButton: {
    alignItems: "center",
    backgroundColor: colors.primaryDark,
    borderRadius: radius.round,
    flexDirection: "row",
    gap: 4,
    minHeight: 36,
    paddingHorizontal: spacing.sm,
  },
  orderProposalButtonText: {
    color: colors.card,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  orderProposalField: {
    flex: 0.55,
    gap: 4,
    minWidth: 112,
  },
  orderProposalFieldWide: {
    flex: 1,
    gap: 4,
    minWidth: 170,
  },
  orderProposalForm: {
    alignItems: "flex-end",
    backgroundColor: "#F8FAFC",
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: spacing.sm,
    padding: spacing.md,
  },
  orderProposalInput: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: radius.md,
    borderWidth: 1,
    color: colors.textPrimary,
    fontFamily: fonts.medium,
    fontSize: typography.small,
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  orderProposalLabel: {
    color: colors.textSecondary,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  orderProposalSubmit: {
    minWidth: 150,
  },
  orderProposalWaiting: {
    alignItems: "center",
    backgroundColor: "#EFF6FF",
    borderBottomColor: "#BFDBFE",
    borderBottomWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  orderProposalWaitingText: {
    color: colors.info,
    flex: 1,
    fontFamily: fonts.medium,
    fontSize: typography.caption,
    lineHeight: 18,
  },
  statusPill: {
    backgroundColor: colors.primarySoft,
    borderRadius: radius.round,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  statusText: {
    color: colors.primaryDark,
    fontFamily: fonts.bold,
    fontSize: typography.caption,
    fontWeight: "700",
  },
  subtitle: {
    color: colors.textSecondary,
    fontFamily: fonts.regular,
    fontSize: typography.body,
    lineHeight: 21,
  },
  title: {
    color: colors.textPrimary,
    fontFamily: fonts.extraBold,
    fontSize: 28,
    fontWeight: "800",
    letterSpacing: 0,
    lineHeight: 34,
  },
});
