import { Router } from "express";
import { adminAuthRoutes } from "./admin-auth.routes.js";
import { adminBonusRoutes } from "./admin-bonus.routes.js";
import { adminCategoriesRoutes } from "./admin-categories.routes.js";
import { adminDashboardRoutes } from "./admin-dashboard.routes.js";
import { adminFiscalRoutes } from "./admin-fiscal.routes.js";
import { adminFraudRoutes } from "./admin-fraud.routes.js";
import { adminKycRoutes } from "./admin-kyc.routes.js";
import { adminLedgerRoutes } from "./admin-ledger.routes.js";
import { adminMerchantsRoutes } from "./admin-merchants.routes.js";
import { adminNetworkRoutes } from "./admin-network.routes.js";
import { adminPaymentsRoutes } from "./admin-payments.routes.js";
import { adminSegmentsRoutes } from "./admin-segments.routes.js";
import { adminServiceTypesRoutes } from "./admin-service-types.routes.js";
import { adminSettingsRoutes } from "./admin-settings.routes.js";
import { adminUsersRoutes } from "./admin-users.routes.js";
import { adminWalletRoutes } from "./admin-wallet.routes.js";
import { adminWithdrawalsRoutes } from "./admin-withdrawals.routes.js";
import { adminAuthMiddleware } from "../middlewares/admin-auth.middleware.js";

export const adminRoutes = Router();

adminRoutes.use("/auth", adminAuthRoutes);
adminRoutes.use(adminAuthMiddleware);
adminRoutes.use("/dashboard", adminDashboardRoutes);
adminRoutes.use("/users", adminUsersRoutes);
adminRoutes.use("/categories", adminCategoriesRoutes);
adminRoutes.use("/segments", adminSegmentsRoutes);
adminRoutes.use("/service-types", adminServiceTypesRoutes);
adminRoutes.use("/kyc", adminKycRoutes);
adminRoutes.use("/merchants", adminMerchantsRoutes);
adminRoutes.use("/payments", adminPaymentsRoutes);
adminRoutes.use("/wallet", adminWalletRoutes);
adminRoutes.use("/ledger", adminLedgerRoutes);
adminRoutes.use("/withdrawals", adminWithdrawalsRoutes);
adminRoutes.use("/network", adminNetworkRoutes);
adminRoutes.use("/bonus", adminBonusRoutes);
adminRoutes.use("/fraud", adminFraudRoutes);
adminRoutes.use("/fiscal", adminFiscalRoutes);
adminRoutes.use("/settings", adminSettingsRoutes);
