import { Router } from "express";
import { authRoutes } from "./auth.routes.js";
import { bonusRoutes } from "./bonus.routes.js";
import { courierRoutes } from "./courier.routes.js";
import { deliveriesRoutes } from "./deliveries.routes.js";
import { kycRoutes } from "./kyc.routes.js";
import { marketplaceRoutes } from "./marketplace.routes.js";
import { merchantRoutes } from "./merchant.routes.js";
import { networkRoutes } from "./network.routes.js";
import { notificationsRoutes } from "./notifications.routes.js";
import { ordersRoutes } from "./orders.routes.js";
import { paymentsRoutes } from "./payments.routes.js";
import { personalChatsRoutes } from "./personal-chats.routes.js";
import { sellerRoutes } from "./seller.routes.js";
import { supportRoutes } from "./support.routes.js";
import { serviceChatsRoutes } from "./service-chats.routes.js";
import { storeChatsRoutes } from "./store-chats.routes.js";
import { usersRoutes } from "./users.routes.js";
import { walletRoutes } from "./wallet.routes.js";
import { withdrawalsRoutes } from "./withdrawals.routes.js";
import { authMiddleware } from "../middlewares/auth.middleware.js";

export const appRoutes = Router();

appRoutes.use("/auth", authRoutes);
appRoutes.use(authMiddleware);
appRoutes.use("/users", usersRoutes);
appRoutes.use("/kyc", kycRoutes);
appRoutes.use("/merchant", merchantRoutes);
appRoutes.use("/wallets", walletRoutes);
appRoutes.use("/payments", paymentsRoutes);
appRoutes.use("/personal-chats", personalChatsRoutes);
appRoutes.use("/network", networkRoutes);
appRoutes.use("/seller", sellerRoutes);
appRoutes.use("/orders", ordersRoutes);
appRoutes.use("/bonus", bonusRoutes);
appRoutes.use("/withdrawals", withdrawalsRoutes);
appRoutes.use("/courier", courierRoutes);
appRoutes.use("/deliveries", deliveriesRoutes);
appRoutes.use("/marketplace", marketplaceRoutes);
appRoutes.use("/notifications", notificationsRoutes);
appRoutes.use("/support", supportRoutes);
appRoutes.use("/service-chats", serviceChatsRoutes);
appRoutes.use("/store-chats", storeChatsRoutes);
